/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLipanaWebhookRouteImport } from './routes/api/public/lipana-webhook'
import { Route as ApiPublicLipanaStkPushRouteImport } from './routes/api/public/lipana/stk-push'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLipanaWebhookRoute = ApiPublicLipanaWebhookRouteImport.update({
  id: '/api/public/lipana-webhook',
  path: '/api/public/lipana-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLipanaStkPushRoute = ApiPublicLipanaStkPushRouteImport.update({
  id: '/api/public/lipana/stk-push',
  path: '/api/public/lipana/stk-push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/lipana-webhook': typeof ApiPublicLipanaWebhookRoute
  '/api/public/lipana/stk-push': typeof ApiPublicLipanaStkPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/lipana-webhook': typeof ApiPublicLipanaWebhookRoute
  '/api/public/lipana/stk-push': typeof ApiPublicLipanaStkPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/lipana-webhook': typeof ApiPublicLipanaWebhookRoute
  '/api/public/lipana/stk-push': typeof ApiPublicLipanaStkPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/lipana-webhook' | '/api/public/lipana/stk-push'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/lipana-webhook' | '/api/public/lipana/stk-push'
  id:
    | '__root__'
    | '/'
    | '/api/public/lipana-webhook'
    | '/api/public/lipana/stk-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicLipanaWebhookRoute: typeof ApiPublicLipanaWebhookRoute
  ApiPublicLipanaStkPushRoute: typeof ApiPublicLipanaStkPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lipana-webhook': {
      id: '/api/public/lipana-webhook'
      path: '/api/public/lipana-webhook'
      fullPath: '/api/public/lipana-webhook'
      preLoaderRoute: typeof ApiPublicLipanaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lipana/stk-push': {
      id: '/api/public/lipana/stk-push'
      path: '/api/public/lipana/stk-push'
      fullPath: '/api/public/lipana/stk-push'
      preLoaderRoute: typeof ApiPublicLipanaStkPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicLipanaWebhookRoute: ApiPublicLipanaWebhookRoute,
  ApiPublicLipanaStkPushRoute: ApiPublicLipanaStkPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
