/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiPublicLipanaWebhookRouteImport } from './routes/api/public/lipana-webhook'
import { Route as ApiAdminResendMeetEmailRouteImport } from './routes/api/admin/resend-meet-email'
import { Route as ApiAdminIssueCertificateRouteImport } from './routes/api/admin/issue-certificate'
import { Route as ApiPublicLipanaStkPushRouteImport } from './routes/api/public/lipana/stk-push'
import { Route as ApiPublicCertificateTokenRouteImport } from './routes/api/public/certificate.$token'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLipanaWebhookRoute = ApiPublicLipanaWebhookRouteImport.update({
  id: '/api/public/lipana-webhook',
  path: '/api/public/lipana-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResendMeetEmailRoute = ApiAdminResendMeetEmailRouteImport.update({
  id: '/api/admin/resend-meet-email',
  path: '/api/admin/resend-meet-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIssueCertificateRoute =
  ApiAdminIssueCertificateRouteImport.update({
    id: '/api/admin/issue-certificate',
    path: '/api/admin/issue-certificate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLipanaStkPushRoute = ApiPublicLipanaStkPushRouteImport.update({
  id: '/api/public/lipana/stk-push',
  path: '/api/public/lipana/stk-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCertificateTokenRoute =
  ApiPublicCertificateTokenRouteImport.update({
    id: '/api/public/certificate/$token',
    path: '/api/public/certificate/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/issue-certificate': typeof ApiAdminIssueCertificateRoute
  '/api/admin/resend-meet-email': typeof ApiAdminResendMeetEmailRoute
  '/api/public/lipana-webhook': typeof ApiPublicLipanaWebhookRoute
  '/api/public/certificate/$token': typeof ApiPublicCertificateTokenRoute
  '/api/public/lipana/stk-push': typeof ApiPublicLipanaStkPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/issue-certificate': typeof ApiAdminIssueCertificateRoute
  '/api/admin/resend-meet-email': typeof ApiAdminResendMeetEmailRoute
  '/api/public/lipana-webhook': typeof ApiPublicLipanaWebhookRoute
  '/api/public/certificate/$token': typeof ApiPublicCertificateTokenRoute
  '/api/public/lipana/stk-push': typeof ApiPublicLipanaStkPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/issue-certificate': typeof ApiAdminIssueCertificateRoute
  '/api/admin/resend-meet-email': typeof ApiAdminResendMeetEmailRoute
  '/api/public/lipana-webhook': typeof ApiPublicLipanaWebhookRoute
  '/api/public/certificate/$token': typeof ApiPublicCertificateTokenRoute
  '/api/public/lipana/stk-push': typeof ApiPublicLipanaStkPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/login'
    | '/admin/'
    | '/api/admin/issue-certificate'
    | '/api/admin/resend-meet-email'
    | '/api/public/lipana-webhook'
    | '/api/public/certificate/$token'
    | '/api/public/lipana/stk-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/login'
    | '/admin'
    | '/api/admin/issue-certificate'
    | '/api/admin/resend-meet-email'
    | '/api/public/lipana-webhook'
    | '/api/public/certificate/$token'
    | '/api/public/lipana/stk-push'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/login'
    | '/admin/'
    | '/api/admin/issue-certificate'
    | '/api/admin/resend-meet-email'
    | '/api/public/lipana-webhook'
    | '/api/public/certificate/$token'
    | '/api/public/lipana/stk-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminIssueCertificateRoute: typeof ApiAdminIssueCertificateRoute
  ApiAdminResendMeetEmailRoute: typeof ApiAdminResendMeetEmailRoute
  ApiPublicLipanaWebhookRoute: typeof ApiPublicLipanaWebhookRoute
  ApiPublicCertificateTokenRoute: typeof ApiPublicCertificateTokenRoute
  ApiPublicLipanaStkPushRoute: typeof ApiPublicLipanaStkPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lipana-webhook': {
      id: '/api/public/lipana-webhook'
      path: '/api/public/lipana-webhook'
      fullPath: '/api/public/lipana-webhook'
      preLoaderRoute: typeof ApiPublicLipanaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/resend-meet-email': {
      id: '/api/admin/resend-meet-email'
      path: '/api/admin/resend-meet-email'
      fullPath: '/api/admin/resend-meet-email'
      preLoaderRoute: typeof ApiAdminResendMeetEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/issue-certificate': {
      id: '/api/admin/issue-certificate'
      path: '/api/admin/issue-certificate'
      fullPath: '/api/admin/issue-certificate'
      preLoaderRoute: typeof ApiAdminIssueCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lipana/stk-push': {
      id: '/api/public/lipana/stk-push'
      path: '/api/public/lipana/stk-push'
      fullPath: '/api/public/lipana/stk-push'
      preLoaderRoute: typeof ApiPublicLipanaStkPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/certificate/$token': {
      id: '/api/public/certificate/$token'
      path: '/api/public/certificate/$token'
      fullPath: '/api/public/certificate/$token'
      preLoaderRoute: typeof ApiPublicCertificateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminIssueCertificateRoute: ApiAdminIssueCertificateRoute,
  ApiAdminResendMeetEmailRoute: ApiAdminResendMeetEmailRoute,
  ApiPublicLipanaWebhookRoute: ApiPublicLipanaWebhookRoute,
  ApiPublicCertificateTokenRoute: ApiPublicCertificateTokenRoute,
  ApiPublicLipanaStkPushRoute: ApiPublicLipanaStkPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
