// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type RuntimeEnv = {
  VITE_SUPABASE_URL?: string;
  VITE_SUPABASE_PUBLISHABLE_KEY?: string;
};

declare global {
  interface Window {
    __APP_ENV__?: RuntimeEnv;
  }
}

function createSupabaseClient() {
  const runtimeEnv =
    typeof window !== "undefined"
      ? window.__APP_ENV__
      : (globalThis as typeof globalThis & { __APP_ENV__?: RuntimeEnv }).__APP_ENV__;

  // Prefer runtime-injected env from the SSR shell, then fall back to Vite build-time env.
  const SUPABASE_URL =
    runtimeEnv?.VITE_SUPABASE_URL ||
    import.meta.env.VITE_SUPABASE_URL ||
    process.env.SUPABASE_URL ||
    process.env.SB_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    runtimeEnv?.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.SB_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const msg =
      "Missing Supabase environment variables. Ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ / SB_ alternatives) are set.";
    // On the server we must fail loudly. In the browser, defer the failure until the client is actually used
    if (typeof window === "undefined") {
      throw new Error(msg);
    }

    // Browser: return a lazy proxy that throws a clear error when any method/property is accessed.
    // This avoids breaking page render while still giving a descriptive error when the app tries to use Supabase.
    const browserStub: SupabaseClient<Database> = new Proxy(
      {},
      {
        get(_, prop) {
          throw new Error(
            `${msg} Attempted to access Supabase client property or method: ${String(prop)}`,
          );
        },
        apply() {
          throw new Error(msg);
        },
      },
    ) as unknown as SupabaseClient<Database>;

    return browserStub;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

type SupabaseClientType = SupabaseClient<Database>;

let _supabase: SupabaseClientType | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase: SupabaseClientType = new Proxy({} as SupabaseClientType, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
